### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by alexanderadam** [jlelse/ApiExplorer#1]
Hi @jlelse,

I saw that you published [Teleposter](https://f-droid.org/de/packages/telegra.ph/) on [F-Droid](https://f-droid.org/).
Would it be possible to publish [Monety](https://github.com/jlelse/Monety), [ApiExplorer](https://github.com/jlelse/ApiExplorer) and [NewsCatchr](https://github.com/NewsCatchr/NewsCatchr) as well on [F-Droid](https://f-droid.org/)?

Thank you in advance

PS: is there any particular reason why [the Monety repository](https://github.com/jlelse/Monety) has "Issues" disabled?

**Comment by jlelse** [comment]
Issues on Monety are enabled again.

I'm currently pausing development on all apps except of Teleposter. Once I restart it, that might be an option.

**Comment by alexanderadam** [comment]
Wow, you answer fast! :+1: 

> Issues on Monety are enabled again.

Awesome

> Once I restart it, that might be an option.

Sounds good. However, are you sure that `closed` is the correct state for this issue in that case?
If you are indeed considering to publish those apps, it is probably better to keep it open, isn't it?
Otherwise nobody will remember that there is indeed still an open issue. :wink:

**Comment by jlelse** [comment]
My brain will remember me once I get back to those apps :wink:

**Comment by alexanderadam** [comment]
Ich hoffe, dass Du Recht behälst :wink:
